### ISSUE TITLE
Vignette is broken

### ISSUE THREAD

**Issue by artur-sannikov** [EBI-Metagenomics/HoloFoodR#11]
Vignette does exists but not available in RStudio.

```R
vignette("HoloFoodR")
```

```
Warning message:
vignette ‘HoloFoodR’ not found 
```

**Comment by TuomasBorman** [comment]
I think `devtools` does not build vignettes by default (From Bioc and CRAN you can get the vignettes by default, I believe)

`devtools::install_github("microbiome/HoloFoodR", build_vignettes=TRUE)`
