### ISSUE TITLE
Include animal metadata in `colData()`

### ISSUE THREAD

**Issue by artur-sannikov** [EBI-Metagenomics/HoloFoodR#14]
Animals have metadata. For example, a salmon [here](https://www.holofooddata.org/animal/SAMEA112949440), or chicken [here](https://www.holofooddata.org/animal/SAMEA112905066) under Sample --> Sample metadata.

Some algorithms like MOFA can use colData variables as group variables (see [OMA book)](https://microbiome.github.io/OMA/docs/devel/pages/23_multi-assay_analyses.html), so this data can included as metadata.

Chickens also have "Pen" metadata.

**Comment by TuomasBorman** [comment]
https://github.com/EBI-Metagenomics/HoloFoodR/pull/17
