### ISSUE TITLE
Additional genome features in v1.1 of HoloFood portal

### ISSUE THREAD

**Issue by SandyRogers** [EBI-Metagenomics/HoloFoodR#30]
The latest release of the HoloFood data portal includes two new features which may be interesting to integrate into HoloFoodR:

1. Genomes now have CAZyme annotations available directly via the HoloFood API: [docs](https://docs.holofooddata.org/website.html#mag-annotations)
2. Genomes now have a relationship to samples, based on the presence of (some of) each genome's sequences in samples. This is essentially a pre-computed search / a map, rather than a live search feature [docs](https://docs.holofooddata.org/website.html#mag-containment-within-samples)

There are new API endpoints for these features, which work in much the same way as the existing endpoints from v1.0.

**Comment by TuomasBorman** [comment]
Thank you! I will take a closer look when time allows

-Tuomas

**Comment by TuomasBorman** [comment]
Thanks! The package was already working / it already fetched those endpoints. I improved the documentation so that user can find them from the output.
